### ISSUE TITLE
Compilation error in classy.nim

### ISSUE THREAD

**Issue by bluenote10** [vegansk/jnim#22]
I'm trying to run the basic example, but I'm getting:

    /home/user/.nimble/pkgs/classy-0.0.1/classy.nim(175, 11) template/generic instantiation from here
    /home/user/.nimble/pkgs/classy-0.0.1/classy.nim(116, 8) Error: type mismatch: got (string, NimNode)
    but expected one of: 
    proc error(msg: string)

This also happens if I have a source file consisting of just the line:

    import jnim

and compiling it with `nim c test.nim`.

Am I doing something wrong? I'm using Nim 0.15.2 (no devel). I have installed `jnim` in the two steps:

    nimble install nimboost@"0.3.2"
    nimble install jnim

(because the latest version of `nimboost` would require Nim devel)

**Comment by nigredo-tori** [comment]
Fixed [classy](http://github.com/nigredo-tori/classy) to support Nim v0.15.2, bumped its version. Didn't bump `nimfp` (since it doesn't depend on any new features), so you'll have to update classy manually:
```
$ nimble install -y classy
```

**Comment by bluenote10** [comment]
Works fine for me, thanks!
