### ISSUE TITLE
stale jnienv/vm

### ISSUE THREAD

**Issue by iffy** [vegansk/jnim#50]
## The problem

In my NDK-based Nim Android app, Java/JNI is complaining that I'm using `JNIEnv*`s from the wrong thread.  I'm producing the Nim c files **without** `--threads:on`. 

I can work around the errors by doing:

```nim
theEnv = nil
```

I run this first thing when handling a JNI call from Java to get rid of the threading errors.  But I can't help thinking that I'm leaking JNIEnv handles.  What are some better options?

**Comment by yglukhov** [comment]
Well, I would bet that you're using jnim from multiple threads. E.g. initializing (loading .so) in the main thread, and calling the problematic function in another thread. Also why are you not using `--threads:on`? I think it should help.

**Comment by iffy** [comment]
I'm not using `--threads:on` because in the process of getting my app to even launch, `--threads:on` would result in the app crashing without any traceback.  Now that I have it mostly working, I'll work on getting a `--threads:on` version to work if you think that would solve my problem.

Regarding multiple threads, I really need to learn better what Android is doing.  I'm not explicitly using any threads, but perhaps the components and functions I'm calling are.  Here's all my Java code https://github.com/iffy/wiish/blob/master/wiishpkg/building/data/android-webview/app/src/main/java/org/wiish/exampleapp/WiishActivity.java

**Comment by yglukhov** [comment]
please retest with latest master

**Comment by iffy** [comment]
I've finally turned `--threads:on`, but I'm still encountering all kinds of problems.  Could you help me understand when I should/should not call the following?  I'm mostly calling C/Nim code from Java, not the other way around.

- `initJNI()`
- `initJNIThread()`
- `deinitJNIThread()`
- `checkInit()`

For instance, do I do this in every call from Java to my code?

```nim
proc myproc() =
  initJNIThread()
  # do my things
  deinitJNIThread()
```

My android app which loads a nim-made library repeatedly restarts after I call `deinitJNIThread()`

**Comment by yglukhov** [comment]
If the thread is long living, just use `checkInit()` at the beginning of every exported function, and don't bother to deinit. Note though that this is a pretty lowlevel approach. I'd recommend to try out a new (experimental) way of implementing java in nim: https://github.com/yglukhov/jnim/blob/master/tests/test_jni_export.nim. Compiling the project with `jexport` will emit a Jnim.java (customizable with `-d:jnimGlue=MyFile.java` flag) file which you'll have to compile along with your java files.

**Comment by yglukhov** [comment]
Almost forgot. Entirely foreign thread functions also require the nim GC init (see `setupForeignThreadGC` in std lib)

**Comment by iffy** [comment]
@yglukhov Thank you for all your help.  I think I finally have it working in a stable way.

I'm using `--gc:regions`, so `setupForeignThreadGC` isn't available.  But using `checkInit()` (and fixing some thread problems in my Java code) has made it work!
