### ISSUE TITLE
Error: 'initJNIThread' is not GC-safe as it performs an indirect call here

### ISSUE THREAD

**Issue by mrhdias** [vegansk/jnim#53]
When compile nimx for android with "nake droid".
I get the following error message:

/home/hdias/.nimble/pkgs/jnim-0.4.2/private/jni_api.nim(67, 18) Error: 'initJNIThread' is not GC-safe as it performs an indirect call here

**Comment by kidandcat** [comment]
Same for me on Windows:
`C:\Users\jairo\.nimble\pkgs\jnim-0.4.2\private\jni_api.nim(67, 18) Error: 'initJNIThread' is not GC-safe as it performs an indirect call here`

**Comment by yglukhov** [comment]
Should be fixed now
