### ISSUE TITLE
Crashes on Android when getting a callback from Java

### ISSUE THREAD

**Issue by dom96** [vegansk/jnim#61]
I'm probably just missing something, but whenever I call back a native function I define in my Nim code from Java and do anything that involves the GC in that callback I get SIGSEGVs.

Here is an example stack trace of one in the Android Studio debugger, in the meantime I guess I'll have to reimplement the `jstring` `$` proc to not use strings. Other ideas welcome :)

![image](https://user-images.githubusercontent.com/246651/78476992-7c936900-773c-11ea-942f-88632a1ccc2d.png)

**Comment by yglukhov** [comment]
What is your threading model? E.g. if youre using sdl or glfm, your main nim thread is secondary to android ui thread, and if the callback is called on the ui thread, that's essentially a peviously unknown foreign thread to nim, where the gc hasnt been initialized.

**Comment by dom96** [comment]
Ahh, that's almost definitely the problem. I suppose I just need to make sure I call `https://nim-lang.org/docs/system.html#setupForeignThreadGc` in my callbacks?

I wonder if there is something we could do to make this more obvious to noobs like me that didn't connect the dots with Android's threading model and how Nim interacts with it.

**Comment by yglukhov** [comment]
At some point jexport will take care of the GC, but it still would be a different thread, and this is not specific to nim really, but to sdl/glfm/etc. So regardless of the language you still have to be aware of that. Dunno maybe we can play around with some gcsafety or other effects that would prevent exported procs to access global vars, but then again it might be totally legal to do so if your nim main thread matches android's.

**Comment by dom96** [comment]
> Dunno maybe we can play around with some gcsafety or other effects that would prevent exported procs to access global vars, but then again it might be totally legal to do so if your nim main thread matches android's.

Hrm, does that mean the GC is using global vars implicitly? FWIW I was getting crashes without accessing anything that was global IIRC.

**Comment by yglukhov** [comment]
> Hrm, does that mean the GC is using global vars implicitly?

No, I just meant we might utilize effect tracking somehow, but that's just a random idea which I don't know if will work, don't take it too seriously.

> FWIW I was getting crashes without accessing anything that was global IIRC.

Well the GC heap is kinda global (but thread-local). So allocating/garbage-collecting objects in an uninitialized thread might lead to crashes.

**Comment by dom96** [comment]
@yglukhov while you're replying to me, this is off-topic, but in some ways likely related. I attempted to use emscripten to get my game running but kept getting crashes (in GC code IIRC). Do you have any tips on what I should avoid for emscripten to work with Nim?

**Comment by yglukhov** [comment]
Yes.
1. Disable it early on, like this: https://github.com/yglukhov/nimx/blob/afc1fbd5fb8baf14472462f4de61413d52ca0e8a/nimx/private/windows/emscripten_window.nim#L462
2. Call it from your main loop, close to stack bottom preferrably in realtime mode, like this: https://github.com/yglukhov/nimx/blob/afc1fbd5fb8baf14472462f4de61413d52ca0e8a/nimx/private/windows/emscripten_window.nim#L436-L449
