### ISSUE TITLE
Android 10 breaks jnim linking with JVMLib

### ISSUE THREAD

**Issue by ftsf** [vegansk/jnim#70]
I was successfully using jnim with Android 9, but Android 10 now crashes without error upon trying to do anything with jnim.

```nim
import jnim

jclass net.impbox.nico.nicoActivity of JVMObject:
  proc openURL(url: string) {.`static`.}

proc openURL*(url: string) =
  nicoActivity.openURL(url)
```

```
Exception : JVM could not be loaded
    C:\myCode\android.nim(7) openURL
    C:\Users\user\.nimble\pkgs\jnim-0.5.1\jnim\private\jni_generator.nim(483) openURL
    C:\Users\user\.nimble\pkgs\jnim-0.5.1\jnim\private\jni_generator.nim(391) getJVMClassForType
    C:\Users\user\.nimble\pkgs\jnim-0.5.1\jnim\private\jni_api.nim(99) getByFqcn
    C:\Users\user\.nimble\pkgs\jnim-0.5.1\jnim\private\jni_api.nim(80) findRunningVM
    C:\Users\user\.nimble\pkgs\jnim-0.5.1\jnim\private\jni_wrapper.nim(521) linkWithJVMLib
```

I don't have an Android 10 device but I was able to reproduce this issue on an Android Virtual Device through Android Studio.

I was unable to find any mentions of changes to the JNI interface between Android 9 and 10.

**Comment by yglukhov** [comment]
Yes, on later androids you have to init `jnim.theEnv` before using jnim. You can get it e.g. by implementing `JNI_OnLoad` in your dynamic library.

**Comment by ftsf** [comment]
@yglukhov Thanks! I was able to get it working on Android 10 with the following.

Though I did have to modify jnim to export `theVM` in order to set it. Should there be a way to set it?

```nim
import jnim

proc JNI_OnLoad*(vm: JavaVMPtr, reserved: pointer): jni.jint {.JNIEXPORT.} =
  jnim.theVM = vm
  return JNI_VERSION_1_6

initJNI()

jclass net.impbox.nico.nicoActivity of JVMObject:
  proc openURL(url: string) {.`static`.}

proc openURL*(url: string) =
  nicoActivity.openURL(url)
```

**Comment by yglukhov** [comment]
Not sure really, `theVM` is used only to get the `Env`.
I think jnim could expose something like `proc setVM(vm: JavaVMPtr)` and `proc setEnv(env: JavaEnvPtr)` so that the users call whatever of those.
I'll add it eventually. But for now you can get the env out of vm to set `theEnv`.
